#!/bin/bash
function checkBrokenSymLink {
    file=$1
    if [ -L $file ]
    then
        if [ ! -e $file ]
        then
            echo $file
        fi
    fi
}

function recursiveVisit {
    directory=$1
    pushd $directory > /dev/null
    for curFile in *
    do
        checkBrokenSymLink $curFile
        if [ -d $curFile ]
            then
                recursiveVisit $curFile
            fi
    done
    popd > /dev/null 
}

ARGV=$@
for curFile in $ARGV
do
    checkBrokenSymLink $curFile
    if [ -d $curFile ] 
        then
            recursiveVisit $curFile
        fi
done
