#!/bin/bash
filename="qwe.txt"

touch oldFile.tmp
count=0
while [ $count -lt 2 ]; do
    if   diff $filename oldFile.tmp > /dev/null  ; then
        let "count = $count + 1"
    else
        cat $filename > oldFile.tmp
        count=0
    fi
    cat  oldFile.tmp
    echo
    sleep 1
done
